# Generated by Django 5.0.12 on 2025-02-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Closing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.IntegerField(verbose_name='Control')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('monitoring_date', models.DateField(verbose_name='Monitoring Date')),
                ('process_type', models.CharField(max_length=50, verbose_name='Process Type')),
                ('process_number', models.CharField(max_length=100, verbose_name='Process Number')),
                ('document_date', models.DateField(verbose_name='Document Date')),
                ('ordinance_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordinance Number')),
                ('ordinance_date', models.DateField(blank=True, null=True, verbose_name='Ordinance Date')),
                ('origin', models.CharField(max_length=100, verbose_name='Origin')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('history', models.TextField(blank=True, null=True, verbose_name='History')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference')),
                ('street_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Street Type')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Neighborhood')),
                ('administrative_region', models.CharField(max_length=50, verbose_name='Administrative Region')),
                ('exit_1', models.DateField(blank=True, null=True, verbose_name='Exit 1 Date')),
                ('destination_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Destination 1')),
                ('return_1', models.DateField(blank=True, null=True, verbose_name='Return 1 Date')),
                ('exit_2', models.DateField(blank=True, null=True, verbose_name='Exit 2 Date')),
                ('destination_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Destination 2')),
                ('return_2', models.DateField(blank=True, null=True, verbose_name='Return 2 Date')),
                ('exit_3', models.DateField(blank=True, null=True, verbose_name='Exit 3 Date')),
                ('destination_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Destination 3')),
                ('return_3', models.DateField(blank=True, null=True, verbose_name='Return 3 Date')),
                ('exit_4', models.DateField(blank=True, null=True, verbose_name='Exit 4 Date')),
                ('destination_4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Destination 4')),
                ('return_4', models.DateField(blank=True, null=True, verbose_name='Return 4 Date')),
                ('exit_5', models.DateField(blank=True, null=True, verbose_name='Exit 5 Date')),
                ('destination_5', models.CharField(blank=True, max_length=255, null=True, verbose_name='Destination 5')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Fechamento',
                'ordering': ['control'],
            },
        ),
    ]
