# Generated by Django 5.0.12 on 2025-02-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0001_create_closures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tipo',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='closing',
            name='address',
            field=models.CharField(max_length=255, verbose_name='ENDEREÇO'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='administrative_region',
            field=models.CharField(max_length=50, verbose_name='AP'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='control',
            field=models.IntegerField(verbose_name='CONTROLE'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='destination_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DESTINO 1'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='destination_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DESTINO 2'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='destination_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DESTINO 3'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='destination_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DESTINO 4'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='destination_5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DESTINO 5'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='document_date',
            field=models.DateField(verbose_name='DATA DO DOC.'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='exit_1',
            field=models.DateField(blank=True, null=True, verbose_name='SAIDA 1'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='exit_2',
            field=models.DateField(blank=True, null=True, verbose_name='SAIDA 2'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='exit_3',
            field=models.DateField(blank=True, null=True, verbose_name='SAIDA 3'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='exit_4',
            field=models.DateField(blank=True, null=True, verbose_name='SAIDA 4'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='exit_5',
            field=models.DateField(blank=True, null=True, verbose_name='SAIDA 5'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='HISTORICO'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='monitoring_date',
            field=models.DateField(verbose_name='MONITOR'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='neighborhood',
            field=models.CharField(max_length=100, verbose_name='BAIRRO'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='ordinance_date',
            field=models.DateField(blank=True, null=True, verbose_name='DATA DA PORTARIA OU AUTORIZACAO'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='ordinance_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº DA PORTARIA'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='origin',
            field=models.CharField(max_length=100, verbose_name='ORIGEM'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='process_number',
            field=models.CharField(max_length=100, verbose_name='NUMERO'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='process_type',
            field=models.CharField(max_length=50, verbose_name='TIPO'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='REFERENCIA'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='return_1',
            field=models.DateField(blank=True, null=True, verbose_name='RETORNO 1'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='return_2',
            field=models.DateField(blank=True, null=True, verbose_name='RETORNO 2'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='return_3',
            field=models.DateField(blank=True, null=True, verbose_name='RETORNO 3'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='return_4',
            field=models.DateField(blank=True, null=True, verbose_name='RETORNO 4'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='status',
            field=models.CharField(max_length=50, verbose_name='STATUS'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='street',
            field=models.CharField(max_length=255, verbose_name='LOGRADOURO'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='street_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TIPO'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='year',
            field=models.IntegerField(verbose_name='ANO'),
        ),
    ]
