# Generated by Django 5.0.12 on 2025-02-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0002_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closing',
            name='process_type',
        ),
    ]
