# Generated by Django 5.0.12 on 2025-02-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0003_remove_process_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
