# Generated by Django 5.0.12 on 2025-02-12 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0005_create_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Closing',
        ),
    ]
