# Generated by Django 5.0.12 on 2025-02-12 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0006_remove_clousures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.IntegerField(verbose_name='CONTROLE')),
                ('year', models.IntegerField(verbose_name='ANO')),
                ('monitoring_date', models.DateField(verbose_name='MONITOR')),
                ('process_number', models.CharField(max_length=100, verbose_name='NUMERO')),
                ('document_date', models.DateField(verbose_name='DATA DO DOC.')),
                ('ordinance_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº DA PORTARIA')),
                ('ordinance_date', models.DateField(blank=True, null=True, verbose_name='DATA DA PORTARIA OU AUTORIZACAO')),
                ('origin', models.CharField(max_length=100, verbose_name='ORIGEM')),
                ('status', models.CharField(max_length=50, verbose_name='STATUS')),
                ('history', models.TextField(blank=True, null=True, verbose_name='HISTORICO')),
                ('street', models.CharField(max_length=255, verbose_name='LOGRADOURO')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='REFERENCIA')),
                ('street_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='TIPO')),
                ('address', models.CharField(max_length=255, verbose_name='ENDEREÇO')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='BAIRRO')),
                ('administrative_region', models.CharField(max_length=50, verbose_name='AP')),
                ('exit_1', models.DateField(blank=True, null=True, verbose_name='SAIDA 1')),
                ('destination_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='DESTINO 1')),
                ('return_1', models.DateField(blank=True, null=True, verbose_name='RETORNO 1')),
                ('exit_2', models.DateField(blank=True, null=True, verbose_name='SAIDA 2')),
                ('destination_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='DESTINO 2')),
                ('return_2', models.DateField(blank=True, null=True, verbose_name='RETORNO 2')),
                ('exit_3', models.DateField(blank=True, null=True, verbose_name='SAIDA 3')),
                ('destination_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='DESTINO 3')),
                ('return_3', models.DateField(blank=True, null=True, verbose_name='RETORNO 3')),
                ('exit_4', models.DateField(blank=True, null=True, verbose_name='SAIDA 4')),
                ('destination_4', models.CharField(blank=True, max_length=255, null=True, verbose_name='DESTINO 4')),
                ('return_4', models.DateField(blank=True, null=True, verbose_name='RETORNO 4')),
                ('exit_5', models.DateField(blank=True, null=True, verbose_name='SAIDA 5')),
                ('destination_5', models.CharField(blank=True, max_length=255, null=True, verbose_name='DESTINO 5')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closures', to='closures.type', verbose_name='Tipo Documento')),
            ],
            options={
                'verbose_name': 'Fechamento',
                'ordering': ['control'],
            },
        ),
    ]
