# Generated by Django 5.0.12 on 2025-02-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0007_create_clousures'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Closing',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
