# Generated by Django 5.0.12 on 2025-02-12 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0009_create_helpers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='ANO')),
                ('monitoring_date', models.DateField(verbose_name='MONITOR')),
                ('process_number', models.CharField(max_length=100, verbose_name='NUMERO')),
                ('document_date', models.DateField(verbose_name='DATA DO DOC.')),
                ('ordinance_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº DA PORTARIA')),
                ('ordinance_date', models.DateField(blank=True, null=True, verbose_name='DATA DA PORTARIA OU AUTORIZACAO')),
                ('history', models.TextField(blank=True, null=True, verbose_name='HISTORICO')),
                ('street', models.CharField(max_length=255, verbose_name='LOGRADOURO')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='REFERENCIA')),
                ('address', models.CharField(max_length=255, verbose_name='ENDEREÇO')),
                ('exit_1', models.DateField(blank=True, null=True, verbose_name='SAIDA 1')),
                ('return_1', models.DateField(blank=True, null=True, verbose_name='RETORNO 1')),
                ('exit_2', models.DateField(blank=True, null=True, verbose_name='SAIDA 2')),
                ('return_2', models.DateField(blank=True, null=True, verbose_name='RETORNO 2')),
                ('exit_3', models.DateField(blank=True, null=True, verbose_name='SAIDA 3')),
                ('return_3', models.DateField(blank=True, null=True, verbose_name='RETORNO 3')),
                ('exit_4', models.DateField(blank=True, null=True, verbose_name='SAIDA 4')),
                ('return_4', models.DateField(blank=True, null=True, verbose_name='RETORNO 4')),
                ('exit_5', models.DateField(blank=True, null=True, verbose_name='SAIDA 5')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('croqui', models.TextField(blank=True, null=True, verbose_name='JSON')),
                ('portaria', models.FileField(blank=True, null=True, upload_to='concierge/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closures', to='closures.ap', verbose_name='AP')),
                ('closuretype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closures', to='closures.closuretype', verbose_name='Tipo Fechamento')),
                ('destination_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_1_closures', to='closures.origin', verbose_name='Destino 1')),
                ('destination_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_2_closures', to='closures.origin', verbose_name='Destino 2')),
                ('destination_3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_3_closures', to='closures.origin', verbose_name='Destino 3')),
                ('destination_4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_4_closures', to='closures.origin', verbose_name='Destino 4')),
                ('destination_5', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_5_closures', to='closures.origin', verbose_name='Destino 5')),
                ('documenttype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closures', to='closures.documenttype', verbose_name='Tipo Documento')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closures', to='closures.neighborhood', verbose_name='Bairro')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closures', to='closures.origin', verbose_name='Origem')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closures', to='closures.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Fechamento',
                'ordering': ['id'],
            },
        ),
    ]
