# Generated by Django 5.0.12 on 2025-02-12 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0010_create_closures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closing',
            name='destination_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_1_closures', to='closures.origin', verbose_name='Destino 1'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='destination_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_2_closures', to='closures.origin', verbose_name='Destino 2'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='destination_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_3_closures', to='closures.origin', verbose_name='Destino 3'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='destination_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_4_closures', to='closures.origin', verbose_name='Destino 4'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='destination_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_5_closures', to='closures.origin', verbose_name='Destino 5'),
        ),
    ]
